<ul class="level-<?php echo $level; ?>">
<?php foreach ($this->getChildren() as $child): ?>
    <li id="<?php echo md5($child->getPath(true)); ?>">
        <a href="<?php echo $child->getPath(true); ?>">
            <?php echo $child->name; ?>
            <?php if ($child->hasChildren()): ?>
                <span class="icon icon-angle-right menu-expand"></span>
            <?php endif; ?>
        </a>
        <?php if ($child->hasChildren()): ?>
            <?php echo $child->asHtml($level + 1); ?>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>

