<ul class="level-<?php echo $level; ?>">
<?php foreach ($node->getChildren() as $child): ?>
    <li>
        <a href="<?php echo $child->getPath(true); ?>">
            <?php echo $child->getName(); ?>
            <?php if ($child->hasChildren()): ?>
                <span class="icon icon-angle-down"></span>
            <?php endif; ?>
        </a>
        <?php if ($child->hasChildren()): ?>
            <?php echo $child->getChildLinksHtml($level + 1); ?>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
</ul>

