<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width,initial-scale=1, maximum-scale=1, user-scalable=no">
        <title><?php if ($currentNode): ?><?php echo $currentNode->getName(); ?><?php else: ?>404<?php endif; ?></title>
        <link rel="stylesheet" type="text/css" href="/css/styles.css"/>
        <script type="text/javascript" src="/js.js"></script>
    </head>
    <body>
        <div class="navigation" id="menu">
            <div id="navLink">
                <span class="open">☰</span>
                <span class="close">×</span>
            </div>
            <div class="inner">
                <div class="search">
                    <input type="text" id="search" placeholder="Search" autocomplete="off"/>
                    <span class="icon icon-search"></span>
                    <div id="searchResult"></div>
                </div>
                <nav>
                    <?php echo $navigationHtml; ?>
                </nav>
            </div>
        </div>
        <div class="row no-margin">
            <div class="container">
                <div class="sixteen columns">
                    <div class="box">
                        <div class="box-inner">
                            <?php if ($currentNode): ?>
                                <div>
                                    <?php echo $currentNode->getCrumbsHtml(); ?>
                                <?php if ($document = $currentNode->getDocument()): ?>
                                    <?php echo $document->asHtml(); ?>
                                <?php else: ?>
                                    <h1><?php echo $currentNode->getName(); ?></h1>
                                <?php endif; ?>
                                </div>

                                <?php if ($currentNode->hasChildren()): ?>
                                <ul class="list buttons-list">
                                    <?php foreach ($currentNode->getChildren() as $child): ?>
                                    <li>
                                        <a href="<?php echo $child->getPath(true); ?>" class="button button-primary"><?php echo $child->getName(); ?></a>
                                    </li>
                                    <?php endforeach; ?>
                                </ul>
                                <?php endif; ?>
                            <?php else: ?>
                                <h1>404</h1>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
        //<![CDATA[
            (function (global) {
                global.search = new global.Search('search', 'searchResult', 'searchSuggestions');
                global.menu = new global.Menu('menu');
                global.app = new global.App();
            })(window);
        //]]>
        </script>
    </body>
</html>

