<!DOCTYPE HTML>
<html>
    <head>
        <meta charset="utf-8" />
        <title><?php if ($currentNode): ?><?php echo $currentNode->getName(); ?><?php else: ?>404<?php endif; ?></title>
        <link rel="stylesheet" type="text/css" href="/css/styles.css"/>
        <script type="text/javascript" src="/js.js"></script>
    </head>
    <body>
        <nav class="navigation">
            <a href="#" id="navLink">
                <span class="open">☰</span>
                <span class="close">×</span>
            </a>
            <div class="search">
                <input type="text" id="search" placeholder="Search" autocomplete="off"/>
                <span class="icon icon-search"></span>
                <div id="searchResult"></div>
            </div>
            <?php echo $navigationHtml; ?>
        </nav>
        <!--div class="header row no-margin">
            <div class="container">
                <div class="sixteen columns">
                    <div class="box">
                        <div class="box-inner">
                            <ul class="list">
                                <li><a href="#">Breadcrumb</a></li>
                                <li><a href="#">Breadcrumb</a></li>
                                <li><a href="#">Breadcrumb</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div-->
        <div class="row no-margin">
            <div class="container">
                <div class="sixteen columns">
                    <div class="box">
                        <div class="box-inner">
                            <?php if ($currentNode): ?>
                                <div>
                                    <?php echo $currentNode->getCrumbsHtml(); ?>
                                <?php if ($document = $currentNode->getDocument()): ?>
                                    <?php echo $document->asHtml(); ?>
                                <?php else: ?>
                                    <h1><?php echo $currentNode->getName(); ?></h1>
                                <?php endif; ?>
                                </div>

                                <?php if ($currentNode->hasChildren()): ?>
                                <ul>
                                    <?php foreach ($currentNode->getChildren() as $child): ?>
                                    <li>
                                        <a href="<?php echo $child->getPath(true); ?>"><?php echo $child->getName(); ?></a>
                                    </li>
                                    <?php endforeach; ?>
                                </ul>
                                <?php endif; ?>
                            <?php else: ?>
                                <h1>404</h1>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!--div class="footer row no-margin">
            <div class="container">
                <div class="sixteen columns">
                    <div class="box">
                        <div class="box-inner">
                            <p>Footer text</p>
                        </div>
                    </div>
                </div>
            </div>
        </div-->
        <script type="text/javascript">
        //<![CDATA[
            (function (global) {
                global.search = new global.Search('search', 'searchResult', 'searchSuggestions');
                global.menu = new global.Menu();
            })(window);
        //]]>
        </script>
    </body>
</html>

